In [1]:
import numpy as np
array =np.array([[1,2],[3,4]])
print("1.2*2 array")

1. 2x2 array:
 [[1 2]
 [3 4]]


In [3]:
random=np.random.rand(3,4)
print("Random 3*4 array : ",random)

Random 3*4 array :  [[0.52636255 0.74909832 0.80673897 0.57038297]
 [0.99552984 0.48196407 0.15531076 0.43436277]
 [0.35096584 0.08731538 0.11473723 0.75543221]]


In [4]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print("\n3. Array of ones:\n", ones_array)
print("\nArray of zeroes:\n", zeros_array)


3. Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
random_6x3 = np.random.rand(6, 3)
transpose_array = random_6x3.T
print("\n4. Random 6x3 array:\n", random_6x3)
print("\nTransposed array (3x6):\n", transpose_array)


4. Random 6x3 array:
 [[0.77168263 0.34014802 0.93052615]
 [0.78290334 0.06170828 0.01049469]
 [0.99986215 0.6987015  0.58343889]
 [0.47553937 0.27612065 0.05512133]
 [0.84023325 0.1873122  0.67704014]
 [0.20569761 0.18689514 0.26731648]]

Transposed array (3x6):
 [[0.77168263 0.78290334 0.99986215 0.47553937 0.84023325 0.20569761]
 [0.34014802 0.06170828 0.6987015  0.27612065 0.1873122  0.18689514]
 [0.93052615 0.01049469 0.58343889 0.05512133 0.67704014 0.26731648]]


In [6]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)
print("\n5. Matrix A (n x p):\n", A)
print("\nMatrix B (p x m):\n", B)
print("\nDot product (n x m):\n", dot_product)


5. Matrix A (n x p):
 [[0.97699435 0.26968375 0.87020342]
 [0.80027212 0.56101766 0.13087923]]

Matrix B (p x m):
 [[0.60857943 0.63466031 0.30484187 0.61917602]
 [0.66881951 0.10498293 0.95070509 0.96686065]
 [0.40653564 0.55016984 0.97270985 0.39006935]]

Dot product (n x m):
 [[1.12871712 1.1271314  1.40067393 1.20511775]
 [0.91545578 0.63880403 0.90462631 1.08898718]]
